### ISSUE TITLE
What does storeExperience ?

### ISSUE THREAD

**Issue by jiwidi** [noahgolmant/DQN#3]
Hi, i'm reading your code and everything is clear for me except for 
```
   def storeExperience(self, state, action, reward, newState, terminalState):
        self.replayMemory.append((state, action, reward, newState, terminalState))
```

I can't figure out why you use it every 100 steps, which purpose it has?

**Comment by noahgolmant** [comment]
This stores an experience (state, action, reward, next state tuple) in the experience replay buffer, from which I sample minibatches to train the network. This decorrelates the data and helps stabilize training (technique is taken from the DQN paper)
